import sqlite3

class equipements :
    def __init__(self, CODE_COMMUNE, NOM_COMMUNE, NUMERO_INSTALLATION, NOM_INSTALLATION, ID_EQUIPEMENTS, NOM_EQUIPEMENTS, AUCUN_ACCES_HANDICAPE_M, AUCUN_ACCES_HANDICAPE_S, GPS_X, GPS_Y):
        self.CODE_COMMUNE = CODE_COMMUNE
        self.NOM_COMMUNE = NOM_COMMUNE
        self.NUMERO_INSTALLATION = NUMERO_INSTALLATION
        self.NOM_INSTALLATION = NOM_INSTALLATION
        self.ID_EQUIPEMENTS = ID_EQUIPEMENTS
        self.NOM_EQUIPEMENTS = NOM_EQUIPEMENTS
        self.AUCUN_ACCES_HANDICAPE_M = AUCUN_ACCES_HANDICAPE_M
        self.AUCUN_ACCES_HANDICAPE_S = AUCUN_ACCES_HANDICAPE_S
        self.GPS_X = GPS_X
        self.GPS_Y = GPS_Y

class installations :
    def __init__(self, NOM_INSTALLATIONS, NUMERO_INSTALLATON, NOM_COMMUNE, CODE_INSEE, CODE_POSTAL, LIEU_DIT, NUMERO_VOIE, NOM_VOIE, LOCATION, LONGITUDE, LATITUDE, AMENAGEMENT_ACCESSIBILITE, ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE, ACCESSIBILITE_HANDICAPE_SENSORIEL, PLACE_PARKING, PLACE_PARKING_HANDICAPE, INSTALLATION_PARTICULIERE, NB_EQUIPEMENTS_SPORTIFS):
        self.NOM_INSTALLATIONS = NOM_INSTALLATIONS
        self.NUMERO_INSTALLATON = NUMERO_INSTALLATON
        self.NOM_COMMUNE = CODE_INSEE
        self.CODE_POSTAL = CODE_POSTAL
        self.LIEU_DIT = LIEU_DIT
        self.NUMERO_VOIE = NUMERO_VOIE
        self.NOM_VOIE = NOM_VOIE
        self.LOCATION = LOCATION
        self.LONGITUDE = LONGITUDE
        self.LATITUDE = LATITUDE
        self.AMENAGEMENT_ACCESSIBILITE = AMENAGEMENT_ACCESSIBILITE
        self.ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE = ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE
        self.ACCESSIBILITE_HANDICAPE_SENSORIEL = ACCESSIBILITE_HANDICAPE_SENSORIEL
        self.PLACE_PARKING = PLACE_PARKING
        self.PLACE_PARKING_HANDICAPE = PLACE_PARKING_HANDICAPE
        self.INSTALLATION_PARTICULIERE = INSTALLATION_PARTICULIERE
        self.NB_EQUIPEMENTS_SPORTIFS = NB_EQUIPEMENTS_SPORTIFS

class equipements_activites :
    def __init__(self, CODE_COMMUNE, NOM_COMMUNE, ID_EQUIPEMENTS, ID_ACTIVITES, NOM_ACTIVITES, NIVEAU_ACTIVITE):
        self.CODE_COMMUNE = CODE_COMMUNE
        self.NOM_COMMUNE = NOM_COMMUNE
        self.ID_EQUIPEMENTS = ID_EQUIPEMENTS
        self.ID_ACTIVITES = ID_ACTIVITES
        self.NOM_ACTIVITES = NOM_ACTIVITES
        self.NIVEAU_ACTIVITE = NIVEAU_ACTIVITE

conn = sqlite3.connect("projet_python.db")
c = conn.cursor()




"""class data:
    def __init__(self, code, label):
        self.code = code
        self.label = label

activity = data(1, "B")


c.execute("CREATE TABLE ")

insert_query = "INSERT INTO test_table(code, label) VALUES (?, ?)"

c.execute(insert_query, (activity.code, activity.label))"""
conn.commit()
conn.close()
