#!/usr/bin/env python
# -*- coding: utf-8 -*-

class installation :
    def __init__(self, NUMERO_INSTALLATON, NOM_INSTALLATIONS, NOM_COMMUNE, CODE_POSTAL, LIEU_DIT, NUMERO_VOIE, NOM_VOIE,
                 LONGITUDE, LATITUDE, AUCUN_AMENAGEMENT_ACCESSIBILITE, ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE,
                 ACCESSIBILITE_HANDICAPE_SENSORIEL, PLACE_PARKING, PLACE_PARKING_HANDICAPE, INSTALLATION_PARTICULIERE):
        self.NOM_INSTALLATIONS = NOM_INSTALLATIONS
        self.NUMERO_INSTALLATON = NUMERO_INSTALLATON
        self.CODE_POSTAL = CODE_POSTAL
        self.LIEU_DIT = LIEU_DIT
        self.NUMERO_VOIE = NUMERO_VOIE
        self.NOM_VOIE = NOM_VOIE
        self.LONGITUDE = LONGITUDE
        self.LATITUDE = LATITUDE
        self.ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE = ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE
        self.ACCESSIBILITE_HANDICAPE_SENSORIEL = ACCESSIBILITE_HANDICAPE_SENSORIEL
        self.PLACE_PARKING = PLACE_PARKING
        self.PLACE_PARKING_HANDICAPE = PLACE_PARKING_HANDICAPE
        self.INSTALLATION_PARTICULIERE = INSTALLATION_PARTICULIERE

    """ Permet d'ajouter une installation dans la base de donnée """

    def add_installation(self, conn):
        insertQuery = "INSERT INTO installations(NOM_INSTALLATIONS, NUMERO_INSTALLATON, CODE_POSTAL, LIEU_DIT, NUMERO_VOIE, " \
                                                "NOM_VOIE, LONGITUDE, LATITUDE, ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE, " \
                                                "ACCESSIBILITE_HANDICAPE_SENSORIEL, PLACE_PARKING, PLACE_PARKING_HANDICAPE," \
                                                "INSTALLATION_PARTICULIERE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)"
        conn.execute(insertQuery, ( self.NOM_INSTALLATIONS, self.NUMERO_INSTALLATON, self.CODE_POSTAL, self.LIEU_DIT, self.NUMERO_VOIE,
                                    self.NOM_VOIE, self.LONGITUDE, self.LATITUDE, self.ACCESSIBILITE_HANDICAPE_MOBILITE_REDUITE,
                                    self.ACCESSIBILITE_HANDICAPE_SENSORIEL, self.PLACE_PARKING, self.PLACE_PARKING_HANDICAPE,
                                    self.INSTALLATION_PARTICULIERE ))
